# Generated by Django 3.2.6 on 2022-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='tiny_url',
        ),
        migrations.AlterField(
            model_name='url',
            name='last_request_date',
            field=models.DateTimeField(verbose_name='last seen date'),
        ),
    ]
