# Generated by Django 3.2.6 on 2022-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_url', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=300)),
                ('counter', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('last_request_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
